name: Branch name

on:
  push:

jobs:
  branch-name:
    runs-on: ubuntu-latest
    outputs:
        output1: ${{ steps.step1.outputs.test }}

    steps:
        - id: step1
          run: echo ${{ github.ref }} >> "$GITHUB_OUTPUT"