name: Branch name

on:
  push:
    branches:
      - main

jobs:
  branch-name:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: step Super Linter Python
        run: '${{ github.ref}}'
