name: Branch name

on:
  push:

jobs:
  branch-name:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout 
          uses: actions/checkout@v3
  
        - name:  Branch Name
          run:  ${{ github.ref }}