name: workflow 2

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: job1
        env:
          BRANCH_NAME: ${{ github.job }}
        run: "echo : $BRANCH_NAME"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: job2
        env:
          BRANCH_NAME: ${{ github.job }}
        run: "echo : $BRANCH_NAME"
