name: workflow 1

on:
  push:

jobs:
  branch-name:
    runs-on: ubuntu-latest

    steps:
        - name: Branch Name
          env:
            BRANCH_NAME: ${{ github.ref }}
          run: "echo current branch : $BRANCH_NAME"